import React from 'react'
import PropTypes from 'prop-types'
import { TypeValidator } from './util/type-validators.js';
import { UiNode } from './types/ui-node.js';
import { Side, SystemIcon } from './types/enums.js';
import mapProperties from '../properties-mapping.js';

export function Button (props) {
  return React.createElement('button', mapProperties('Button', props));
}

Button.propTypes = {
  ...UiNode.PropTypes,

  children: PropTypes.string.isRequired,
  width: PropTypes.number,
  height: PropTypes.number,
  outline: PropTypes.bool,
  fontSize: PropTypes.number,
  textColor: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.number,
    PropTypes.arrayOf(TypeValidator.arrayOf(4)),
    PropTypes.exact({
      h:PropTypes.number.isRequired,
      s: PropTypes.number.isRequired,
      l: PropTypes.number.isRequired
    }),
    PropTypes.exact({
      l: PropTypes.number.isRequired,
      c: PropTypes.number.isRequired,
      h: PropTypes.number.isRequired
    }),
    PropTypes.exact({
      c: PropTypes.number.isRequired,
      m: PropTypes.number.isRequired,
      y: PropTypes.number.isRequired,
      k: PropTypes.number.isRequired
    }),
    PropTypes.exact({
      r: PropTypes.number.isRequired,
      g: PropTypes.number.isRequired,
      b: PropTypes.number.isRequired,
      a: PropTypes.number.isRequired,
      type: PropTypes.string
    }),
  ]),
  textSide: PropTypes.oneOf([
    Side.bottom,
    Side.left,
    Side.right,
    Side.top
  ]),
  iconColor: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.number,
    PropTypes.arrayOf(TypeValidator.arrayOf(4)),
    PropTypes.exact({
      h:PropTypes.number.isRequired,
      s: PropTypes.number.isRequired,
      l: PropTypes.number.isRequired
    }),
    PropTypes.exact({
      l: PropTypes.number.isRequired,
      c: PropTypes.number.isRequired,
      h: PropTypes.number.isRequired
    }),
    PropTypes.exact({
      c: PropTypes.number.isRequired,
      m: PropTypes.number.isRequired,
      y: PropTypes.number.isRequired,
      k: PropTypes.number.isRequired
    }),
    PropTypes.exact({
      r: PropTypes.number.isRequired,
      g: PropTypes.number.isRequired,
      b: PropTypes.number.isRequired,
      a: PropTypes.number.isRequired,
      type: PropTypes.string
    }),
  ]),
  iconPath: PropTypes.string,
  iconSize: PropTypes.arrayOf(TypeValidator.arrayOf(2)),
  iconType: PropTypes.oneOf([
      SystemIcon['6Dof'],
      SystemIcon.actions,
      SystemIcon.actionsLeft,
      SystemIcon.actionsOff,
      SystemIcon.actionsRight,
      SystemIcon.add,
      SystemIcon.addressBook,
      SystemIcon.albumAdd,
      SystemIcon.albumRemove,
      SystemIcon.alphabetical,
      SystemIcon.analytics,
      SystemIcon.arrowDown,
      SystemIcon.arrowLeft,
      SystemIcon.arrowRight,
      SystemIcon.arrowUp,
      SystemIcon.autoPlacement,
      SystemIcon.backspace,
      SystemIcon.battery,
      SystemIcon.block,
      SystemIcon.blockCamera,
      SystemIcon.blockCookie,
      SystemIcon.blockLocation,
      SystemIcon.blockMicrophone,
      SystemIcon.bluetooth,
      SystemIcon.bluetoothOff,
      SystemIcon.bookmark,
      SystemIcon.bookmarkAdd,
      SystemIcon.brightness,
      SystemIcon.calendar,
      SystemIcon.camera,
      SystemIcon.cameraIris,
      SystemIcon.carriageReturn,
      SystemIcon.chat,
      SystemIcon.check,
      SystemIcon.checkSelection,
      SystemIcon.chevronDown,
      SystemIcon.chevronLeft,
      SystemIcon.chevronRight,
      SystemIcon.chevronUp,
      SystemIcon.clipboard,
      SystemIcon.clock,
      SystemIcon.close,
      SystemIcon.closedCaption,
      SystemIcon.cloud,
      SystemIcon.cloudOff,
      SystemIcon.collection,
      SystemIcon.controller,
      SystemIcon.cookie,
      SystemIcon.copy,
      SystemIcon.creditCard,
      SystemIcon.cut,
      SystemIcon.cvCameraPrivilege,
      SystemIcon.doNotDisturb,
      SystemIcon.dot,
      SystemIcon.download,
      SystemIcon.downloadCloud,
      SystemIcon.dropdown,
      SystemIcon.edit,
      SystemIcon.effectsPalette,
      SystemIcon.eject,
      SystemIcon.emoji,
      SystemIcon.enter,
      SystemIcon.exit,
      SystemIcon.extraction,
      SystemIcon.eyeTracking,
      SystemIcon.fastForward,
      SystemIcon.fastForwardTenSecond,
      SystemIcon.file,
      SystemIcon.filter,
      SystemIcon.flag,
      SystemIcon.flagChina,
      SystemIcon.flagFrance,
      SystemIcon.flagGermany,
      SystemIcon.flagJapan,
      SystemIcon.flagSouthKorea,
      SystemIcon.flagUk,
      SystemIcon.flagUsa,
      SystemIcon.follow,
      SystemIcon.frame,
      SystemIcon.gameController,
      SystemIcon.genericThreeDimensional,
      SystemIcon.grid,
      SystemIcon.hamburger,
      SystemIcon.handOrientationLeft,
      SystemIcon.handOrientationRight,
      SystemIcon.heart,
      SystemIcon.heartAdd,
      SystemIcon.help,
      SystemIcon.history,
      SystemIcon.home,
      SystemIcon.image,
      SystemIcon.info,
      SystemIcon.keyboard,
      SystemIcon.keyboardCapital,
      SystemIcon.keyboardLanguage,
      SystemIcon.keyboardLetter,
      SystemIcon.keyboardNumber,
      SystemIcon.link,
      SystemIcon.listView,
      SystemIcon.localAreaServer,
      SystemIcon.marqueeSelection,
      SystemIcon.merge,
      SystemIcon.mesh,
      SystemIcon.microphone,
      SystemIcon.microphoneMute,
      SystemIcon.minimize,
      SystemIcon.mobile,
      SystemIcon.more,
      SystemIcon.move,
      SystemIcon.multipleSelection,
      SystemIcon.music,
      SystemIcon.musicPause,
      SystemIcon.musicPlay,
      SystemIcon.networkServer,
      SystemIcon.next,
      SystemIcon.notification,
      SystemIcon.objectRecognition,
      SystemIcon.openWith,
      SystemIcon.origin,
      SystemIcon.passableWorld,
      SystemIcon.paste,
      SystemIcon.pause,
      SystemIcon.permission,
      SystemIcon.person,
      SystemIcon.personAdd,
      SystemIcon.personBlock,
      SystemIcon.personFollow,
      SystemIcon.personThree,
      SystemIcon.personTwo,
      SystemIcon.personUnFollow,
      SystemIcon.personVoip,
      SystemIcon.phone,
      SystemIcon.phoneEndCall,
      SystemIcon.phoneIncomingCall,
      SystemIcon.phoneSwitchCall,
      SystemIcon.pin,
      SystemIcon.placeholderBluetooth,
      SystemIcon.play,
      SystemIcon.playlistRepeatOff,
      SystemIcon.playlistRepeatOn,
      SystemIcon.playlistRepeatSong,
      SystemIcon.playlistShuffle,
      SystemIcon.playlistShuffleOff,
      SystemIcon.power,
      SystemIcon.previous,
      SystemIcon.privacy,
      SystemIcon.privateView,
      SystemIcon.publicView,
      SystemIcon.rearrange,
      SystemIcon.refresh,
      SystemIcon.replay,
      SystemIcon.report,
      SystemIcon.resize,
      SystemIcon.restoreMedia,
      SystemIcon.revolver,
      SystemIcon.rewindTenSecond,
      SystemIcon.screenshot,
      SystemIcon.search,
      SystemIcon.securityLock,
      SystemIcon.securityNotSecure,
      SystemIcon.securityUnlock,
      SystemIcon.send,
      SystemIcon.settings,
      SystemIcon.share,
      SystemIcon.shareScreen,
      SystemIcon.shiftDisabled,
      SystemIcon.shiftEnabled,
      SystemIcon.shiftEnabledPermanent,
      SystemIcon.sleep,
      SystemIcon.slideShow,
      SystemIcon.snooze,
      SystemIcon.space,
      SystemIcon.star,
      SystemIcon.stop,
      SystemIcon.stream,
      SystemIcon.streamOff,
      SystemIcon.summon,
      SystemIcon.tablet,
      SystemIcon.tabNew,
      SystemIcon.tabNewImage,
      SystemIcon.tabViewAll,
      SystemIcon.tag,
      SystemIcon.text,
      SystemIcon.thumbsDown,
      SystemIcon.thumbsDownLeft,
      SystemIcon.thumbsDownRight,
      SystemIcon.thumbsUp,
      SystemIcon.thumbsUpLeft,
      SystemIcon.thumbsUpRight,
      SystemIcon.topChart,
      SystemIcon.trash,
      SystemIcon.undoReply,
      SystemIcon.unknownDevice,
      SystemIcon.update,
      SystemIcon.upload,
      SystemIcon.uploadCloud,
      SystemIcon.view,
      SystemIcon.viewSource,
      SystemIcon.voiceFeedback,
      SystemIcon.voip,
      SystemIcon.volume,
      SystemIcon.volumeMute,
      SystemIcon.warning,
      SystemIcon.webXr,
      SystemIcon.wifi,
      SystemIcon.wifiNoBar,
      SystemIcon.wifiNoSignal,
      SystemIcon.wifiOff,
      SystemIcon.wifiOneBar,
      SystemIcon.wifiSecure,
      SystemIcon.wifiSecureNoBar,
      SystemIcon.wifiSecureNoSignal,
      SystemIcon.wifiSecureOneBar,
      SystemIcon.wifiUnknown,
      SystemIcon.windowNew,
      SystemIcon.windowPopUpBlock,
      SystemIcon.windowViewAll,
      SystemIcon.work,
      SystemIcon.workspaces,
      SystemIcon.zoomIn,
      SystemIcon.zoomOut
  ])
};

Button.defaultProps = {
  ...UiNode.DefaultProps,

  children: '',
  width: 0,
  height: 0,
  outline: false,
  fontSize: 0.08,
  textColor: 'white',
  textSide: Side.left,
  iconColor: 'white',
  iconSize: [0.05, 0.05],
};
