// Copyright (c) 2019 Magic Leap, Inc. All Rights Reserved

import { input } from 'lumin';

/**
 * @exports KeyCodes
 * @description Represents Magic-Script - Lumin Runtime KeyCodes mapping.
 */
export const KeyCodes = {
    'akeycode-0': input.KeyCodes.AKEYCODE_0,
    'akeycode-1': input.KeyCodes.AKEYCODE_1,
    'akeycode-2': input.KeyCodes.AKEYCODE_2,
    'akeycode-3': input.KeyCodes.AKEYCODE_3,
    'akeycode-4': input.KeyCodes.AKEYCODE_4,
    'akeycode-5': input.KeyCodes.AKEYCODE_5,
    'akeycode-6': input.KeyCodes.AKEYCODE_6,
    'akeycode-7': input.KeyCodes.AKEYCODE_7,
    'akeycode-8': input.KeyCodes.AKEYCODE_8,
    'akeycode-9': input.KeyCodes.AKEYCODE_9,
    'akeycode-A': input.KeyCodes.AKEYCODE_A,
    'akeycode-B': input.KeyCodes.AKEYCODE_B,
    'akeycode-C': input.KeyCodes.AKEYCODE_C,
    'akeycode-D': input.KeyCodes.AKEYCODE_D,
    'akeycode-E': input.KeyCodes.AKEYCODE_E,
    'akeycode-F': input.KeyCodes.AKEYCODE_F,
    'akeycode-G': input.KeyCodes.AKEYCODE_G,
    'akeycode-H': input.KeyCodes.AKEYCODE_H,
    'akeycode-I': input.KeyCodes.AKEYCODE_I,
    'akeycode-J': input.KeyCodes.AKEYCODE_J,
    'akeycode-K': input.KeyCodes.AKEYCODE_K,
    'akeycode-L': input.KeyCodes.AKEYCODE_L,
    'akeycode-M': input.KeyCodes.AKEYCODE_M,
    'akeycode-N': input.KeyCodes.AKEYCODE_N,
    'akeycode-O': input.KeyCodes.AKEYCODE_O,
    'akeycode-P': input.KeyCodes.AKEYCODE_P,
    'akeycode-Q': input.KeyCodes.AKEYCODE_Q,
    'akeycode-R': input.KeyCodes.AKEYCODE_R,
    'akeycode-S': input.KeyCodes.AKEYCODE_S,
    'akeycode-T': input.KeyCodes.AKEYCODE_T,
    'akeycode-U': input.KeyCodes.AKEYCODE_U,
    'akeycode-V': input.KeyCodes.AKEYCODE_V,
    'akeycode-W': input.KeyCodes.AKEYCODE_W,
    'akeycode-X': input.KeyCodes.AKEYCODE_X,
    'akeycode-Y': input.KeyCodes.AKEYCODE_Y,
    'akeycode-Z': input.KeyCodes.AKEYCODE_Z,

    'akeycode-alt-left': input.KeyCodes.AKEYCODE_ALT_LEFT,
    'akeycode-alt-right': input.KeyCodes.AKEYCODE_ALT_RIGHT,
    'akeycode-apostrophe': input.KeyCodes.AKEYCODE_APOSTROPHE,
    'akeycode-app-switch': input.KeyCodes.AKEYCODE_APP_SWITCH,
    'akeycode-at': input.KeyCodes.AKEYCODE_AT,
    'akeycode-avr-input': input.KeyCodes.AKEYCODE_AVR_INPUT,
    'akeycode-avr-power': input.KeyCodes.AKEYCODE_AVR_POWER,

    'akeycode-back': input.KeyCodes.AKEYCODE_BACK,
    'akeycode-backslash': input.KeyCodes.AKEYCODE_BACKSLASH,
    'akeycode-bookmark': input.KeyCodes.AKEYCODE_BOOKMARK,
    'akeycode-break': input.KeyCodes.AKEYCODE_BREAK,
    'akeycode-button-1': input.KeyCodes.AKEYCODE_BUTTON_1,
    'akeycode-button-2': input.KeyCodes.AKEYCODE_BUTTON_2,
    'akeycode-button-3': input.KeyCodes.AKEYCODE_BUTTON_3,
    'akeycode-button-4': input.KeyCodes.AKEYCODE_BUTTON_4,
    'akeycode-button-5': input.KeyCodes.AKEYCODE_BUTTON_5,
    'akeycode-button-6': input.KeyCodes.AKEYCODE_BUTTON_6,
    'akeycode-button-7': input.KeyCodes.AKEYCODE_BUTTON_7,
    'akeycode-button-8': input.KeyCodes.AKEYCODE_BUTTON_8,
    'akeycode-button-9': input.KeyCodes.AKEYCODE_BUTTON_9,
    'akeycode-button-10': input.KeyCodes.AKEYCODE_BUTTON_10,
    'akeycode-button-11': input.KeyCodes.AKEYCODE_BUTTON_11,
    'akeycode-button-12': input.KeyCodes.AKEYCODE_BUTTON_12,
    'akeycode-button-13': input.KeyCodes.AKEYCODE_BUTTON_13,
    'akeycode-button-14': input.KeyCodes.AKEYCODE_BUTTON_14,
    'akeycode-button-15': input.KeyCodes.AKEYCODE_BUTTON_15,
    'akeycode-button-16': input.KeyCodes.AKEYCODE_BUTTON_16,
    'akeycode-button-A': input.KeyCodes.AKEYCODE_BUTTON_A,
    'akeycode-button-B': input.KeyCodes.AKEYCODE_BUTTON_B,
    'akeycode-button-C': input.KeyCodes.AKEYCODE_BUTTON_C,
    'akeycode-button-X': input.KeyCodes.AKEYCODE_BUTTON_X,
    'akeycode-button-Y': input.KeyCodes.AKEYCODE_BUTTON_Y,
    'akeycode-button-Z': input.KeyCodes.AKEYCODE_BUTTON_Z,
    'akeycode-button-L1': input.KeyCodes.AKEYCODE_BUTTON_L1,
    'akeycode-button-L2': input.KeyCodes.AKEYCODE_BUTTON_L2,
    'akeycode-button-R1': input.KeyCodes.AKEYCODE_BUTTON_R1,
    'akeycode-button-R2': input.KeyCodes.AKEYCODE_BUTTON_R2,
    'akeycode-button-mode': input.KeyCodes.AKEYCODE_BUTTON_MODE,
    'akeycode-button-select': input.KeyCodes.AKEYCODE_BUTTON_SELECT,
    'akeycode-button-start': input.KeyCodes.AKEYCODE_BUTTON_START,
    'akeycode-button-thumbl': input.KeyCodes.AKEYCODE_BUTTON_THUMBL,
    'akeycode-button-thumbr': input.KeyCodes.AKEYCODE_BUTTON_THUMBR,

    'akeycode-call': input.KeyCodes.AKEYCODE_CALL,
    'akeycode-camera': input.KeyCodes.AKEYCODE_CAMERA,
    'akeycode-caps-lock': input.KeyCodes.AKEYCODE_CAPS_LOCK,
    'akeycode-captions': input.KeyCodes.AKEYCODE_CAPTIONS,
    'akeycode-channel-down': input.KeyCodes.AKEYCODE_CHANNEL_DOWN,
    'akeycode-channel-up': input.KeyCodes.AKEYCODE_CHANNEL_UP,
    'akeycode-clear': input.KeyCodes.AKEYCODE_CLEAR,
    'akeycode-comma': input.KeyCodes.AKEYCODE_COMMA,
    'akeycode-ctrl-left': input.KeyCodes.AKEYCODE_CTRL_LEFT,
    'akeycode-ctrol-right': input.KeyCodes.AKEYCODE_CTRL_RIGHT,

    'akeycode-del': input.KeyCodes.AKEYCODE_DEL,
    'akeycode-dpad-center': input.KeyCodes.AKEYCODE_DPAD_CENTER,
    'akeycode-dpad-down': input.KeyCodes.AKEYCODE_DPAD_DOWN,
    'akeycode-dpad-left': input.KeyCodes.AKEYCODE_DPAD_LEFT,
    'akeycode-dpad-right': input.KeyCodes.AKEYCODE_DPAD_RIGHT,
    'akeycode-dpad-up': input.KeyCodes.AKEYCODE_DPAD_UP,
    'akeycode-dvr': input.KeyCodes.AKEYCODE_DVR,

    'akeycode-endcall': input.KeyCodes.AKEYCODE_ENDCALL,
    'akeycode-enter': input.KeyCodes.AKEYCODE_ENTER,
    'akeycode-envelope': input.KeyCodes.AKEYCODE_ENVELOPE,
    'akeycode-equals': input.KeyCodes.AKEYCODE_EQUALS,
    'akeycode-escape': input.KeyCodes.AKEYCODE_ESCAPE,
    'akeycode-ex-battery': input.KeyCodes.AKEYCODE_EX_BATTERY,
    'akeycode-ex-bumper': input.KeyCodes.AKEYCODE_EX_BUMPER,
    'akeycode-ex-capture': input.KeyCodes.AKEYCODE_EX_CAPTURE,
    'akeycode-ex-home-tap': input.KeyCodes.AKEYCODE_EX_HOME_TAP,
    'akeycode-ex-reality': input.KeyCodes.AKEYCODE_EX_REALITY,
    'akeycode-ex-trigger': input.KeyCodes.AKEYCODE_EX_TRIGGER,
    'akeycode-explorer': input.KeyCodes.AKEYCODE_EXPLORER,

    'akeycode-F1': input.KeyCodes.AKEYCODE_F1,
    'akeycode-F2': input.KeyCodes.AKEYCODE_F2,
    'akeycode-F3': input.KeyCodes.AKEYCODE_F3,
    'akeycode-F4': input.KeyCodes.AKEYCODE_F4,
    'akeycode-F5': input.KeyCodes.AKEYCODE_F5,
    'akeycode-F6': input.KeyCodes.AKEYCODE_F6,
    'akeycode-F7': input.KeyCodes.AKEYCODE_F7,
    'akeycode-F8': input.KeyCodes.AKEYCODE_F8,
    'akeycode-F9': input.KeyCodes.AKEYCODE_F9,
    'akeycode-F10': input.KeyCodes.AKEYCODE_F10,
    'akeycode-F11': input.KeyCodes.AKEYCODE_F11,
    'akeycode-F12': input.KeyCodes.AKEYCODE_F12,
    'akeycode-focus': input.KeyCodes.AKEYCODE_FOCUS, // *Camera* focus
    'akeycode-forward': input.KeyCodes.AKEYCODE_FORWARD,
    'akeycode-forward-del': input.KeyCodes.AKEYCODE_FORWARD_DEL,
    'akeycode-function': input.KeyCodes.AKEYCODE_FUNCTION,

    'akeycode-grave': input.KeyCodes.AKEYCODE_GRAVE,
    'akeycode-guide': input.KeyCodes.AKEYCODE_GUIDE,

    'akeycode-headsethook': input.KeyCodes.AKEYCODE_HEADSETHOOK,
    'akeycode-home': input.KeyCodes.AKEYCODE_HOME,

    'akeycode-info': input.KeyCodes.AKEYCODE_INFO,
    'akeycode-insert': input.KeyCodes.AKEYCODE_INSERT,

    'akeycode-left-bracket': input.KeyCodes.AKEYCODE_LEFT_BRACKET,

    'akeycode-media-close': input.KeyCodes.AKEYCODE_MEDIA_CLOSE,
    'akeycode-media-eject': input.KeyCodes.AKEYCODE_MEDIA_EJECT,
    'akeycode-media-fast-forward': input.KeyCodes.AKEYCODE_MEDIA_FAST_FORWARD,
    'akeycode-media-next': input.KeyCodes.AKEYCODE_MEDIA_NEXT,
    'akeycode-media-pause': input.KeyCodes.AKEYCODE_MEDIA_PAUSE,
    'akeycode-media-play': input.KeyCodes.AKEYCODE_MEDIA_PLAY,
    'akeycode-media-play-pause': input.KeyCodes.AKEYCODE_MEDIA_PLAY_PAUSE,
    'akeycode-media-previous': input.KeyCodes.AKEYCODE_MEDIA_PREVIOUS,
    'akeycode-media-record': input.KeyCodes.AKEYCODE_MEDIA_RECORD,
    'akeycode-media-rewind': input.KeyCodes.AKEYCODE_MEDIA_REWIND,
    'akeycode-media-stop': input.KeyCodes.AKEYCODE_MEDIA_STOP,
    'akeycode-menu': input.KeyCodes.AKEYCODE_MENU,
    'akeycode-meta-left': input.KeyCodes.AKEYCODE_META_LEFT,
    'akeycode-meta-right': input.KeyCodes.AKEYCODE_META_RIGHT,
    'akeycode-minus': input.KeyCodes.AKEYCODE_MINUS,
    'akeycode-move-end': input.KeyCodes.AKEYCODE_MOVE_END,
    'akeycode-mode-home': input.KeyCodes.AKEYCODE_MOVE_HOME,
    'akeycode-mute': input.KeyCodes.AKEYCODE_MUTE,

    'akeycode-notification': input.KeyCodes.AKEYCODE_NOTIFICATION,
    'akeycode-num': input.KeyCodes.AKEYCODE_NUM,
    'akeycode-num-lock': input.KeyCodes.AKEYCODE_NUM_LOCK,
    'akeycode-numpad-0': input.KeyCodes.AKEYCODE_NUMPAD_0,
    'akeycode-numpad-1': input.KeyCodes.AKEYCODE_NUMPAD_1,
    'akeycode-numpad-2': input.KeyCodes.AKEYCODE_NUMPAD_2,
    'akeycode-numpad-3': input.KeyCodes.AKEYCODE_NUMPAD_3,
    'akeycode-numpad-4': input.KeyCodes.AKEYCODE_NUMPAD_4,
    'akeycode-numpad-5': input.KeyCodes.AKEYCODE_NUMPAD_5,
    'akeycode-numpad-6': input.KeyCodes.AKEYCODE_NUMPAD_6,
    'akeycode-numpad-7': input.KeyCodes.AKEYCODE_NUMPAD_7,
    'akeycode-numpad-8': input.KeyCodes.AKEYCODE_NUMPAD_8,
    'akeycode-numpad-9': input.KeyCodes.AKEYCODE_NUMPAD_9,
    'akeycode-numpad-add': input.KeyCodes.AKEYCODE_NUMPAD_ADD,
    'akeycode-numpad-comma': input.KeyCodes.AKEYCODE_NUMPAD_COMMA,
    'akeycode-numpad-divide': input.KeyCodes.AKEYCODE_NUMPAD_DIVIDE,
    'akeycode-numpad-dot': input.KeyCodes.AKEYCODE_NUMPAD_DOT,
    'akeycode-numpad-enter': input.KeyCodes.AKEYCODE_NUMPAD_ENTER,
    'akeycode-numpad-equals': input.KeyCodes.AKEYCODE_NUMPAD_EQUALS,
    'akeycode-numpad-left-paren': input.KeyCodes.AKEYCODE_NUMPAD_LEFT_PAREN,
    'akeycode-numpad-multiplay': input.KeyCodes.AKEYCODE_NUMPAD_MULTIPLY,
    'akeycode-numpad-right-paren': input.KeyCodes.AKEYCODE_NUMPAD_RIGHT_PAREN,
    'akeycode-numpad-substract': input.KeyCodes.AKEYCODE_NUMPAD_SUBTRACT,

    'akeycode-page-down': input.KeyCodes.AKEYCODE_PAGE_DOWN,
    'akeycode-page-up': input.KeyCodes.AKEYCODE_PAGE_UP,
    'akeycode-period': input.KeyCodes.AKEYCODE_PERIOD,
    'akeycode-pictsymbols': input.KeyCodes.AKEYCODE_PICTSYMBOLS,
    'akeycode-plus': input.KeyCodes.AKEYCODE_PLUS,
    'akeycode-pound': input.KeyCodes.AKEYCODE_POUND,
    'akeycode-power': input.KeyCodes.AKEYCODE_POWER,
    'akeycode-prog-blue': input.KeyCodes.AKEYCODE_PROG_BLUE,
    'akeycode-prog-green': input.KeyCodes.AKEYCODE_PROG_GREEN,
    'akeycode-prog-red': input.KeyCodes.AKEYCODE_PROG_RED,
    'akeycode-prog-yellow': input.KeyCodes.AKEYCODE_PROG_YELLOW,

    'akeycode-right-bracket': input.KeyCodes.AKEYCODE_RIGHT_BRACKET,

    'akeycode-scroll-lock': input.KeyCodes.AKEYCODE_SCROLL_LOCK,
    'akeycode-search': input.KeyCodes.AKEYCODE_SEARCH,
    'akeycode-semicolon': input.KeyCodes.AKEYCODE_SEMICOLON,
    'akeycode-settings': input.KeyCodes.AKEYCODE_SETTINGS,
    'akeycode-shift-left': input.KeyCodes.AKEYCODE_SHIFT_LEFT,
    'akeycode-shift-right': input.KeyCodes.AKEYCODE_SHIFT_RIGHT,
    'akeycode-slash': input.KeyCodes.AKEYCODE_SLASH,
    'akeycode-soft-left': input.KeyCodes.AKEYCODE_SOFT_LEFT,
    'akeycode-soft-right': input.KeyCodes.AKEYCODE_SOFT_RIGHT,
    'akeycode-space': input.KeyCodes.AKEYCODE_SPACE,
    'akeycode-star': input.KeyCodes.AKEYCODE_STAR,
    'akeycode-stb-input': input.KeyCodes.AKEYCODE_STB_INPUT,
    'akeycode-stb-power': input.KeyCodes.AKEYCODE_STB_POWER,
    'akeycode-switch-charset': input.KeyCodes.AKEYCODE_SWITCH_CHARSET,
    'akeycode-sym': input.KeyCodes.AKEYCODE_SYM,
    'akeycode-sysrq': input.KeyCodes.AKEYCODE_SYSRQ,

    'akeycode-tab': input.KeyCodes.AKEYCODE_TAB,
    'akeycode-tv': input.KeyCodes.AKEYCODE_TV,
    'akeycode-tv-input': input.KeyCodes.AKEYCODE_TV_INPUT,
    'akeycode-tv-output': input.KeyCodes.AKEYCODE_TV_POWER,

    'akeycode-unknown': input.KeyCodes.AKEYCODE_UNKNOWN,

    'akeycode-volume-down': input.KeyCodes.AKEYCODE_VOLUME_DOWN,
    'akeycode-volume-mute': input.KeyCodes.AKEYCODE_VOLUME_MUTE,
    'akeycode-volume-up': input.KeyCodes.AKEYCODE_VOLUME_UP,

    'akeycode-window': input.KeyCodes.AKEYCODE_WINDOW,

    'akeycode-zoom-in': input.KeyCodes.AKEYCODE_ZOOM_IN,
    'akeycode-zoom-out': input.KeyCodes.AKEYCODE_ZOOM_OUT
}
